Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 30
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	12	bam_index_and_2bw
	1	build_index
	12	feature_count
	12	genome_map
	12	rRNA_map
	12	sam_2_uniquebam
	12	sort_STAR_result
	12	uniquebam_sort_and_index
	86

rule rRNA_map:
    input: /zhounas/zhoulab/backup/xhyu/20171012JL/HB160055-01武汉大学12个人lncRNA建库测序过滤任务单_VIP/ANHB160055_HB160055-01_2017-01-09/Cleandata/PS2/PS2_R1.fq.gz, /zhounas/zhoulab/backup/xhyu/20171012JL/HB160055-01武汉大学12个人lncRNA建库测序过滤任务单_VIP/ANHB160055_HB160055-01_2017-01-09/Cleandata/PS2/PS2_R2.fq.gz
    output: /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/02_mapping/rRNA/PS2/PS2Unmapped.out.mate1, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/02_mapping/rRNA/PS2/PS2Unmapped.out.mate2
    jobid: 72
    wildcards: dataset=PS2, work_dir=/data2/zhoulab/yuxinghai/hg19_jlRNAseq/results
    threads: 20

Error in rule rRNA_map:
    jobid: 72
    output: /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/02_mapping/rRNA/PS2/PS2Unmapped.out.mate1, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/02_mapping/rRNA/PS2/PS2Unmapped.out.mate2

RuleException:
CalledProcessError in line 67 of /data2/zhoulab/yuxinghai/hg19_jlRNAseq/snakemake/hg19_Snakefile.py:
Command ' set -euo pipefail;  STAR --genomeDir /data2/zhoulab/yuxinghai/hg19_jlRNAseq/anno/rRNA --readFilesIn /zhounas/zhoulab/backup/xhyu/20171012JL/HB160055-01武汉大学12个人lncRNA建库测序过滤任务单_VIP/ANHB160055_HB160055-01_2017-01-09/Cleandata/PS2/PS2_R1.fq.gz /zhounas/zhoulab/backup/xhyu/20171012JL/HB160055-01武汉大学12个人lncRNA建库测序过滤任务单_VIP/ANHB160055_HB160055-01_2017-01-09/Cleandata/PS2/PS2_R2.fq.gz --readFilesCommand gunzip -c --runThreadN 20 --outFileNamePrefix /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/02_mapping/rRNA/PS2/PS2 --outReadsUnmapped Fastx --outFilterMatchNmin 40 --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 ' returned non-zero exit status 105
  File "/data2/zhoulab/yuxinghai/hg19_jlRNAseq/snakemake/hg19_Snakefile.py", line 67, in __rule_rRNA_map
  File "/data1/zhoulab/yuxinghai/.conda/envs/py35/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job rRNA_map since they might be corrupted:
/data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/02_mapping/rRNA/PS2/PS2Unmapped.out.mate1, /data2/zhoulab/yuxinghai/hg19_jlRNAseq/results/02_mapping/rRNA/PS2/PS2Unmapped.out.mate2
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data2/zhoulab/yuxinghai/hg19_jlRNAseq/snakemake/.snakemake/log/2018-03-30T091919.641489.snakemake.log
